//! Generate Cargo project files for transpiled MVL programs.

/// Emit a minimal `Cargo.toml` for a transpiled MVL program.
pub fn emit_cargo_toml(crate_name: &str) -> String {
    format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"

# Generated by MVL transpiler (Phase 1)
# Do not edit manually — regenerate with `mvl build`

[[bin]]
name = "{crate_name}"
path = "src/main.rs"
"#
    )
}

/// Emit a `src/main.rs` wrapper that calls into the transpiled library.
pub fn emit_main_rs(entry_fn: Option<&str>) -> String {
    match entry_fn {
        Some(name) => format!(
            r#"// Generated by MVL transpiler (Phase 1)
mod lib;
use lib::*;

fn main() {{
    {name}();
}}
"#
        ),
        None => r#"// Generated by MVL transpiler (Phase 1)
// No `main` function found in MVL source — this is a library crate.
fn main() {
    println!("MVL library (no main fn declared)");
}
"#
        .to_string(),
    }
}
