//! Generate Cargo project files for transpiled MVL programs.

/// Emit `Cargo.toml` for a binary crate (program has `fn main`).
pub fn emit_cargo_toml_binary(crate_name: &str) -> String {
    format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"

# Generated by MVL transpiler (Phase 1)
# Do not edit manually — regenerate with `mvl build`
"#
    )
}

/// Emit `Cargo.toml` for a library crate (no `fn main`).
pub fn emit_cargo_toml_library(crate_name: &str) -> String {
    format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"

# Generated by MVL transpiler (Phase 1)
# Do not edit manually — regenerate with `mvl build`

[lib]
name = "{crate_name}"
path = "src/lib.rs"
"#
    )
}

/// Emit a stub `src/main.rs` for library crates that need a binary entry point.
pub fn emit_main_rs_stub(crate_name: &str) -> String {
    format!(
        r#"// Generated by MVL transpiler (Phase 1)
// No `fn main` in MVL source — library crate.
// Link against {crate_name} to use its functions.
fn main() {{
    println!("mvl library: {crate_name}");
}}
"#
    )
}

// Keep old name for callers that haven't migrated yet.
#[allow(dead_code)]
pub fn emit_cargo_toml(crate_name: &str) -> String {
    emit_cargo_toml_library(crate_name)
}

#[allow(dead_code)]
pub fn emit_main_rs(entry_fn: Option<&str>) -> String {
    match entry_fn {
        Some(name) => format!(
            r#"// Generated by MVL transpiler (Phase 1)
mod lib;
use lib::*;

fn main() {{
    {name}();
}}
"#
        ),
        None => emit_main_rs_stub("mvl_program"),
    }
}
