//! Core code generator: string-builder with indentation tracking.
//!
//! [`Codegen`] is the single writer passed through every emit function.
//! All other `emit_*` modules take `&mut Codegen` and append to it.

use crate::mvl::parser::ast::Decl;
use crate::mvl::parser::ast::Program;
use crate::mvl::transpiler::emit_functions::emit_fn_decl;
use crate::mvl::transpiler::emit_types::emit_security_preamble;
use crate::mvl::transpiler::emit_types::emit_type_decl;

/// Code-generation context: accumulates Rust source text.
#[derive(Default)]
pub struct Codegen {
    buf: String,
    indent: usize,
}

impl Codegen {
    pub fn new() -> Self {
        Self::default()
    }

    /// Finish generation and return the accumulated source string.
    pub fn finish(self) -> String {
        self.buf
    }

    // ── Low-level writers ────────────────────────────────────────────────

    pub fn push(&mut self, s: &str) {
        self.buf.push_str(s);
    }

    pub fn push_char(&mut self, c: char) {
        self.buf.push(c);
    }

    /// Emit a newline.
    pub fn nl(&mut self) {
        self.buf.push('\n');
    }

    /// Emit current indentation (spaces).
    pub fn indent(&mut self) {
        for _ in 0..self.indent * 4 {
            self.buf.push(' ');
        }
    }

    /// Emit indentation + text + newline.
    pub fn line(&mut self, s: &str) {
        self.indent();
        self.buf.push_str(s);
        self.buf.push('\n');
    }

    /// Emit a blank line (just a newline).
    pub fn blank(&mut self) {
        self.buf.push('\n');
    }

    /// Increase indent level.
    pub fn push_indent(&mut self) {
        self.indent += 1;
    }

    /// Decrease indent level (saturating).
    pub fn pop_indent(&mut self) {
        self.indent = self.indent.saturating_sub(1);
    }

    // ── Program-level emit ───────────────────────────────────────────────

    /// Emit a complete Rust file from a [`Program`].
    pub fn emit_program(&mut self, prog: &Program) {
        // File header
        self.line("// Generated by MVL transpiler (Phase 1)");
        self.line("#![allow(dead_code, unused_variables, unused_imports, unused_parens)]");
        self.blank();

        // Security label preamble (Public<T>, Secret<T>, etc.)
        emit_security_preamble(self);
        self.blank();

        // Top-level declarations
        for decl in &prog.declarations {
            match decl {
                Decl::Type(td) => emit_type_decl(self, td),
                Decl::Fn(fd) => emit_fn_decl(self, fd),
                Decl::Const(_) => {
                    // Phase 1: const decls emitted as-is in emit_types if needed
                    // skip for now — const support is limited
                }
                Decl::Module(_) => {
                    // Phase 1: nested modules not yet supported
                }
            }
            self.blank();
        }
    }
}
