// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Schuberg Philis

//! Actor runtime for the LLVM backend.
//!
//! Provides C-ABI functions for actor lifecycle: spawn, send, drop, join_all.
//!
//! Each actor is a std::thread running a message-dispatch loop. The actor state
//! is a heap-allocated raw byte array; the dispatch function is a function pointer
//! with the signature `fn(state_ptr: *mut u8, disc: i64, args: *const i64)`.
//!
//! # Message protocol
//!
//! - `disc` (discriminant): which public behavior to invoke (0-based index in
//!   declaration order)
//! - `args`: array of `i64` values, one per behavior parameter (all MVL scalar
//!   types map to `i64` at the LLVM ABI level; pointer types pass as pointer-width
//!   integers)
//!
//! # Mailbox configuration (#1127)
//!
//! `mvl_actor_spawn` accepts `capacity` and `policy` parameters:
//! - `capacity > 0`: bounded sync_channel(capacity)
//! - `capacity <= 0`: unbounded channel (grows without limit)
//! - `policy = 0`: DropNewest — `try_send`, drop new message when full
//! - `policy = 1`: Block — `send`, block the sender until space is available
//!
//! # Shutdown protocol (#1124)
//!
//! `mvl_actor_join_all()` is emitted at the end of `fn main()` by the LLVM
//! backend. It:
//! 1. Drains the global actor registry (all spawned handles + join handles)
//! 2. Drops each live `MvlActorHandle` — closing the sender
//! 3. Joins all actor threads (which drain buffered messages then exit)
//!
//! `mvl_actor_drop` marks the handle as consumed in the registry (setting its
//! slot to `None`) to prevent double-free when `mvl_actor_join_all` runs later.
//!
//! Phase 8, #696. Shutdown fix: #1124. Mailbox config: #1127.

use std::cell::RefCell;
use std::sync::mpsc;
use std::thread::{self, JoinHandle};

/// Maximum number of `i64` arguments a single behavior call can carry.
/// Behaviors with more parameters than this are not yet supported.
const MAX_ARGS: usize = 8;

/// An in-flight actor message: behavior discriminant + packed i64 arguments.
struct MvlMsg {
    disc: i64,
    args: [i64; MAX_ARGS],
}

/// Typed mailbox sender — captures both channel type and overflow policy (#1127).
enum MvlSender {
    /// Bounded channel, drop-newest policy: `try_send` (fire-and-forget).
    BoundedDrop(mpsc::SyncSender<MvlMsg>),
    /// Bounded channel, blocking policy: `send` (blocks sender when full).
    BoundedBlock(mpsc::SyncSender<MvlMsg>),
    /// Unbounded channel: `send` never blocks (grows without limit).
    Unbounded(mpsc::Sender<MvlMsg>),
}

impl MvlSender {
    fn send_msg(&self, msg: MvlMsg) {
        match self {
            MvlSender::BoundedDrop(tx) => {
                let _ = tx.try_send(msg);
            }
            MvlSender::BoundedBlock(tx) => {
                let _ = tx.send(msg);
            }
            MvlSender::Unbounded(tx) => {
                let _ = tx.send(msg);
            }
        }
    }
}

/// Opaque actor handle allocated on the heap.
///
/// The LLVM backend stores this as a `ptr` (opaque pointer) in LLVM IR.
/// Callers must treat the returned pointer as opaque and only pass it to
/// [`mvl_actor_send`] and [`mvl_actor_drop`].
pub struct MvlActorHandle {
    sender: MvlSender,
}

/// C-ABI dispatch function pointer type.
///
/// ```c
/// void dispatch(void *state, int64_t disc, int64_t const *args);
/// ```
type DispatchFn = unsafe extern "C" fn(*mut u8, i64, *const i64);

/// Global registry of spawned actors.
///
/// Each entry is `(Option<handle_ptr as usize>, JoinHandle<()>)`.
/// The `Option` is set to `None` when the handle has been explicitly freed
/// via `mvl_actor_drop`, preventing double-free in `mvl_actor_join_all`.
///
/// Uses `thread_local!` because LLVM-generated programs spawn actors only from
/// the main thread. `mvl_actor_join_all` is also called from the main thread,
/// so both access the same TLS slot.
thread_local! {
    static ACTOR_REGISTRY: RefCell<Vec<(Option<usize>, JoinHandle<()>)>> =
        const { RefCell::new(Vec::new()) };
}

/// Spawn a new actor thread and return an opaque actor handle.
///
/// # Parameters
///
/// - `dispatch`: the actor's behavior dispatch function
///   (generated by the MVL LLVM backend from `actor` declarations)
/// - `state_ptr`: pointer to the initial actor state struct
/// - `state_size`: byte size of the state struct (used to heap-copy the state)
/// - `capacity`: mailbox capacity — `> 0` for bounded, `<= 0` for unbounded (#1127)
/// - `policy`: overflow policy — `0` = DropNewest (`try_send`), `1` = Block (`send`) (#1127)
///
/// # Returns
///
/// An opaque `*mut MvlActorHandle`, or null on spawn failure.
/// The caller owns the returned pointer and must eventually call [`mvl_actor_drop`]
/// or [`mvl_actor_join_all`] to release it.
///
/// # Safety
///
/// `state_ptr` must point to at least `state_size` valid bytes.
#[no_mangle]
pub unsafe extern "C" fn mvl_actor_spawn(
    dispatch: DispatchFn,
    state_ptr: *mut u8,
    state_size: i64,
    capacity: i64,
    policy: i64,
) -> *mut u8 {
    // Guard: reject negative sizes and null state pointer.
    if state_size < 0 || state_ptr.is_null() {
        return std::ptr::null_mut();
    }
    let size = state_size as usize;
    // Deep-copy the initial state so the actor thread fully owns it.
    let mut state: Vec<u8> = std::slice::from_raw_parts(state_ptr, size).to_vec();

    // Build the typed sender based on capacity and policy (#1127).
    let (sender, rx): (MvlSender, _) = if capacity > 0 {
        let cap = capacity as usize;
        let (tx, rx) = mpsc::sync_channel::<MvlMsg>(cap);
        let sender = if policy == 1 {
            MvlSender::BoundedBlock(tx)
        } else {
            MvlSender::BoundedDrop(tx)
        };
        (sender, rx)
    } else {
        let (tx, rx) = mpsc::channel::<MvlMsg>();
        (MvlSender::Unbounded(tx), rx)
    };

    let handle = Box::new(MvlActorHandle { sender });
    let handle_ptr = Box::into_raw(handle);

    let handle_addr = handle_ptr as usize;
    let join_handle = thread::spawn(move || {
        CURRENT_ACTOR_HANDLE.with(|cell| cell.set(handle_addr));
        let state_ptr = state.as_mut_ptr();
        while let Ok(msg) = rx.recv() {
            dispatch(state_ptr, msg.disc, msg.args.as_ptr());
        }
    });

    // Register (handle_ptr, JoinHandle) so mvl_actor_join_all can drain and join.
    ACTOR_REGISTRY.with(|r| {
        r.borrow_mut()
            .push((Some(handle_ptr as usize), join_handle));
    });

    handle_ptr as *mut u8
}

/// Send a behavior message to an actor (fire-and-forget).
///
/// # Parameters
///
/// - `handle`: opaque actor handle returned by [`mvl_actor_spawn`]
/// - `disc`: behavior discriminant (0-based index of the `pub fn` behavior)
/// - `argc`: number of `i64` arguments in `args`
/// - `args`: pointer to an array of `i64` argument values
///
/// # Safety
///
/// `handle` must be a valid pointer returned by [`mvl_actor_spawn`] and not yet
/// dropped. `args` must point to at least `argc` valid `i64` values.
#[no_mangle]
pub unsafe extern "C" fn mvl_actor_send(handle: *mut u8, disc: i64, argc: i64, args: *const i64) {
    if handle.is_null() {
        return;
    }
    let actor = &*(handle as *const MvlActorHandle);
    let argc = (argc as usize).min(MAX_ARGS);
    let mut msg = MvlMsg {
        disc,
        args: [0i64; MAX_ARGS],
    };
    if argc > 0 {
        let src = std::slice::from_raw_parts(args, argc);
        msg.args[..argc].copy_from_slice(src);
    }
    actor.sender.send_msg(msg);
}

// Thread-local that each actor thread sets to its own handle before processing messages.
use std::cell::Cell;
thread_local! {
    static CURRENT_ACTOR_HANDLE: Cell<usize> = const { Cell::new(0) };
}

/// Return the current actor's own handle (for passing `self` to other actors).
///
/// Must only be called from within a behavior dispatch. Returns null if called
/// from a non-actor thread.
#[no_mangle]
pub extern "C" fn mvl_actor_self() -> *mut u8 {
    CURRENT_ACTOR_HANDLE.with(|cell| cell.get() as *mut u8)
}

/// Drop an actor handle, disconnecting the sender.
///
/// After this call the actor thread will drain any remaining messages and then exit.
/// The handle is marked as consumed in the global registry so that
/// [`mvl_actor_join_all`] does not double-free it.
///
/// # Safety
///
/// `handle` must be a valid pointer returned by [`mvl_actor_spawn`] and must not
/// be used after this call.
#[no_mangle]
pub unsafe extern "C" fn mvl_actor_drop(handle: *mut u8) {
    if handle.is_null() {
        return;
    }
    // Mark the registry entry as consumed so mvl_actor_join_all skips it.
    ACTOR_REGISTRY.with(|r| {
        let mut reg = r.borrow_mut();
        if let Some(entry) = reg.iter_mut().find(|(p, _)| *p == Some(handle as usize)) {
            entry.0 = None;
        }
    });
    drop(Box::from_raw(handle as *mut MvlActorHandle));
}

/// Join all spawned actor threads, waiting for them to drain and exit.
///
/// Emitted at the end of `fn main()` by the LLVM backend (#1124).
///
/// For each registered actor handle that has not been explicitly dropped:
/// 1. Drops the `MvlActorHandle`, closing the `SyncSender`
/// 2. The actor thread drains any buffered messages and exits
///
/// After dropping all handles, joins all actor threads.
#[no_mangle]
pub extern "C" fn mvl_actor_join_all() {
    let entries = ACTOR_REGISTRY.with(|r| r.borrow_mut().drain(..).collect::<Vec<_>>());
    // Drop all live handles first — closes senders so actor threads will exit.
    for (ptr_opt, _) in &entries {
        if let Some(ptr) = ptr_opt {
            unsafe {
                drop(Box::from_raw(*ptr as *mut MvlActorHandle));
            }
        }
    }
    // Join all actor threads.
    for (_, jh) in entries {
        let _ = jh.join();
    }
}
