// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Schuberg Philis

//! Actor runtime for the LLVM backend.
//!
//! Provides C-ABI functions for actor lifecycle: spawn, send, drop.
//!
//! Each actor is a std::thread running a message-dispatch loop. The actor state
//! is a heap-allocated raw byte array; the dispatch function is a function pointer
//! with the signature `fn(state_ptr: *mut u8, disc: i64, args: *const i64)`.
//!
//! # Message protocol
//!
//! - `disc` (discriminant): which public behavior to invoke (0-based index in
//!   declaration order)
//! - `args`: array of `i64` values, one per behavior parameter (all MVL scalar
//!   types map to `i64` at the LLVM ABI level; pointer types pass as pointer-width
//!   integers)
//!
//! # Thread safety
//!
//! The actor thread owns the state exclusively; callers only hold the
//! `MvlActorHandle` which wraps a `SyncSender`. Fire-and-forget semantics:
//! `try_send` drops messages when the queue (capacity 256) is full.
//!
//! Phase 8, #696.

use std::cell::Cell;
use std::sync::mpsc;
use std::thread;

/// Maximum number of `i64` arguments a single behavior call can carry.
/// Behaviors with more parameters than this are not yet supported.
const MAX_ARGS: usize = 8;

/// An in-flight actor message: behavior discriminant + packed i64 arguments.
struct MvlMsg {
    disc: i64,
    args: [i64; MAX_ARGS],
}

/// Opaque actor handle allocated on the heap.
///
/// The LLVM backend stores this as a `ptr` (opaque pointer) in LLVM IR.
/// Callers must treat the returned pointer as opaque and only pass it to
/// [`mvl_actor_send`] and [`mvl_actor_drop`].
pub struct MvlActorHandle {
    sender: mpsc::SyncSender<MvlMsg>,
}

/// C-ABI dispatch function pointer type.
///
/// ```c
/// void dispatch(void *state, int64_t disc, int64_t const *args);
/// ```
type DispatchFn = unsafe extern "C" fn(*mut u8, i64, *const i64);

/// Spawn a new actor thread and return an opaque actor handle.
///
/// # Parameters
///
/// - `dispatch`: the actor's behavior dispatch function
///   (generated by the MVL LLVM backend from `actor` declarations)
/// - `state_ptr`: pointer to the initial actor state struct
/// - `state_size`: byte size of the state struct (used to heap-copy the state)
///
/// # Returns
///
/// An opaque `*mut MvlActorHandle`, or null on spawn failure.
/// The caller owns the returned pointer and must eventually call [`mvl_actor_drop`].
///
/// # Safety
///
/// `state_ptr` must point to at least `state_size` valid bytes.
#[no_mangle]
pub unsafe extern "C" fn mvl_actor_spawn(
    dispatch: DispatchFn,
    state_ptr: *mut u8,
    state_size: i64,
) -> *mut u8 {
    // Guard: reject negative sizes and null state pointer.
    if state_size < 0 || state_ptr.is_null() {
        return std::ptr::null_mut();
    }
    let size = state_size as usize;
    // Deep-copy the initial state so the actor thread fully owns it.
    let mut state: Vec<u8> = std::slice::from_raw_parts(state_ptr, size).to_vec();

    let (tx, rx) = mpsc::sync_channel::<MvlMsg>(256);

    let handle = Box::new(MvlActorHandle { sender: tx });
    let handle_ptr = Box::into_raw(handle);

    let handle_addr = handle_ptr as usize;
    thread::spawn(move || {
        CURRENT_ACTOR_HANDLE.with(|cell| cell.set(handle_addr));
        let state_ptr = state.as_mut_ptr();
        while let Ok(msg) = rx.recv() {
            dispatch(state_ptr, msg.disc, msg.args.as_ptr());
        }
    });

    handle_ptr as *mut u8
}

/// Send a behavior message to an actor (fire-and-forget).
///
/// # Parameters
///
/// - `handle`: opaque actor handle returned by [`mvl_actor_spawn`]
/// - `disc`: behavior discriminant (0-based index of the `pub fn` behavior)
/// - `argc`: number of `i64` arguments in `args`
/// - `args`: pointer to an array of `i64` argument values
///
/// # Safety
///
/// `handle` must be a valid pointer returned by [`mvl_actor_spawn`] and not yet
/// dropped. `args` must point to at least `argc` valid `i64` values.
#[no_mangle]
pub unsafe extern "C" fn mvl_actor_send(handle: *mut u8, disc: i64, argc: i64, args: *const i64) {
    if handle.is_null() {
        return;
    }
    let actor = &*(handle as *const MvlActorHandle);
    let argc = (argc as usize).min(MAX_ARGS);
    let mut msg = MvlMsg {
        disc,
        args: [0i64; MAX_ARGS],
    };
    if argc > 0 {
        let src = std::slice::from_raw_parts(args, argc);
        msg.args[..argc].copy_from_slice(src);
    }
    let _ = actor.sender.try_send(msg);
}

// Thread-local that each actor thread sets to its own handle before processing messages.
thread_local! {
    static CURRENT_ACTOR_HANDLE: Cell<usize> = const { Cell::new(0) };
}

/// Return the current actor's own handle (for passing `self` to other actors).
///
/// Must only be called from within a behavior dispatch. Returns null if called
/// from a non-actor thread.
#[no_mangle]
pub extern "C" fn mvl_actor_self() -> *mut u8 {
    CURRENT_ACTOR_HANDLE.with(|cell| cell.get() as *mut u8)
}

/// Drop an actor handle, disconnecting the sender.
///
/// After this call the actor thread will drain any remaining messages and then exit.
///
/// # Safety
///
/// `handle` must be a valid pointer returned by [`mvl_actor_spawn`] and must not
/// be used after this call.
#[no_mangle]
pub unsafe extern "C" fn mvl_actor_drop(handle: *mut u8) {
    if handle.is_null() {
        return;
    }
    drop(Box::from_raw(handle as *mut MvlActorHandle));
}
