//! `mvl.lock` — lockfile read/write with content hashes.
//!
//! Implements Spec 008 Requirement 4: Lock File.
//!
//! Format (TOML array of tables):
//! ```toml
//! [[package]]
//! name = "github.com/lab271/mvl-stdlib"
//! version = "1.2.0"
//! hash = "sha256:abc123..."
//! commit = "deadbeef"
//! git = "https://github.com/lab271/mvl-stdlib"
//! ```

use std::collections::HashMap;
use std::path::Path;

/// A single locked package entry.
#[derive(Debug, Clone, PartialEq)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    /// SHA256 hash of the source tree: `"sha256:<hex>"`.
    pub hash: String,
    /// Git commit SHA that was fetched.
    pub commit: Option<String>,
    /// The git URL the package was fetched from.
    pub git: Option<String>,
}

/// The full lock file: an ordered list of locked packages.
#[derive(Debug, Clone, Default)]
pub struct LockFile {
    pub packages: Vec<LockedPackage>,
}

impl LockFile {
    /// Load and parse `mvl.lock` from the given directory.
    pub fn load(dir: &Path) -> Result<Self, LockError> {
        let path = dir.join("mvl.lock");
        let content = std::fs::read_to_string(&path)
            .map_err(|e| LockError::Io(path.display().to_string(), e.to_string()))?;
        Self::parse(&content)
    }

    /// Load `mvl.lock` if it exists; return an empty lock file otherwise.
    pub fn load_or_empty(dir: &Path) -> Self {
        Self::load(dir).unwrap_or_default()
    }

    /// Parse a lock file from TOML text.
    pub fn parse(content: &str) -> Result<Self, LockError> {
        let mut packages = Vec::new();
        let mut current: Option<HashMap<String, String>> = None;

        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if line == "[[package]]" {
                if let Some(pkg) = current.take() {
                    packages.push(locked_from_map(pkg)?);
                }
                current = Some(HashMap::new());
                continue;
            }
            if let Some(ref mut map) = current {
                if let Some(eq) = line.find('=') {
                    let key = line[..eq].trim().to_string();
                    let raw_val = line[eq + 1..].trim();
                    if raw_val.starts_with('"') && raw_val.ends_with('"') && raw_val.len() >= 2 {
                        let val = raw_val[1..raw_val.len() - 1].to_string();
                        map.insert(key, val);
                    }
                }
            }
        }
        if let Some(pkg) = current {
            packages.push(locked_from_map(pkg)?);
        }
        Ok(LockFile { packages })
    }

    /// Serialize the lock file to TOML text.
    pub fn to_toml(&self) -> String {
        let mut out = String::new();
        out.push_str("# Generated by mvl. Do not edit manually.\n");
        out.push_str("# Commit this file to source control for reproducible builds.\n");
        for pkg in &self.packages {
            out.push_str("\n[[package]]\n");
            out.push_str(&format!("name = \"{}\"\n", toml_escape(&pkg.name)));
            out.push_str(&format!("version = \"{}\"\n", toml_escape(&pkg.version)));
            out.push_str(&format!("hash = \"{}\"\n", toml_escape(&pkg.hash)));
            if let Some(ref c) = pkg.commit {
                out.push_str(&format!("commit = \"{}\"\n", toml_escape(c)));
            }
            if let Some(ref g) = pkg.git {
                out.push_str(&format!("git = \"{}\"\n", toml_escape(g)));
            }
        }
        out
    }

    /// Write `mvl.lock` to the given directory.
    pub fn write(&self, dir: &Path) -> Result<(), LockError> {
        let path = dir.join("mvl.lock");
        std::fs::write(&path, self.to_toml())
            .map_err(|e| LockError::Io(path.display().to_string(), e.to_string()))
    }

    /// Look up a locked package by name.
    pub fn get(&self, name: &str) -> Option<&LockedPackage> {
        self.packages.iter().find(|p| p.name == name)
    }

    /// Update or insert a locked package entry.
    pub fn upsert(&mut self, pkg: LockedPackage) {
        if let Some(existing) = self.packages.iter_mut().find(|p| p.name == pkg.name) {
            *existing = pkg;
        } else {
            self.packages.push(pkg);
        }
    }

    /// Remove a package entry by name.
    pub fn remove(&mut self, name: &str) {
        self.packages.retain(|p| p.name != name);
    }

    /// Check whether the lock file contains all packages listed in `names`.
    pub fn is_complete(&self, names: &[&str]) -> bool {
        names.iter().all(|n| self.get(n).is_some())
    }
}

#[derive(Debug)]
pub enum LockError {
    Io(String, String),
    MissingField(String),
    InvalidHash(String),
}

impl std::fmt::Display for LockError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LockError::Io(path, e) => write!(f, "cannot read {path}: {e}"),
            LockError::MissingField(n) => write!(f, "mvl.lock: missing field '{n}'"),
            LockError::InvalidHash(h) => write!(f, "mvl.lock: invalid hash '{h}'"),
        }
    }
}

fn locked_from_map(mut map: HashMap<String, String>) -> Result<LockedPackage, LockError> {
    let name = map
        .remove("name")
        .ok_or_else(|| LockError::MissingField("name".to_string()))?;
    let version = map
        .remove("version")
        .ok_or_else(|| LockError::MissingField("version".to_string()))?;
    let hash = map
        .remove("hash")
        .ok_or_else(|| LockError::MissingField("hash".to_string()))?;
    // Validate hash prefix
    if !hash.starts_with("sha256:") {
        return Err(LockError::InvalidHash(hash));
    }
    let commit = map.remove("commit");
    let git = map.remove("git");
    Ok(LockedPackage {
        name,
        version,
        hash,
        commit,
        git,
    })
}

/// Escape a string for use inside a TOML double-quoted value.
fn toml_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"
# Generated by mvl.
# Commit this file to source control for reproducible builds.

[[package]]
name = "github.com/lab271/mvl-stdlib"
version = "1.2.0"
hash = "sha256:abc123def456"
commit = "deadbeef"
git = "https://github.com/lab271/mvl-stdlib"

[[package]]
name = "tls"
version = "0.4.0"
hash = "sha256:aaabbbccc"
"#;

    // ── Existing tests ────────────────────────────────────────────────────────

    #[test]
    fn parse_sample_lock() {
        let lf = LockFile::parse(SAMPLE).unwrap();
        assert_eq!(lf.packages.len(), 2);

        let std = lf.get("github.com/lab271/mvl-stdlib").unwrap();
        assert_eq!(std.version, "1.2.0");
        assert_eq!(std.hash, "sha256:abc123def456");
        assert_eq!(std.commit.as_deref(), Some("deadbeef"));
        assert_eq!(
            std.git.as_deref(),
            Some("https://github.com/lab271/mvl-stdlib")
        );

        let tls = lf.get("tls").unwrap();
        assert_eq!(tls.version, "0.4.0");
        assert!(tls.commit.is_none());
    }

    #[test]
    fn lock_roundtrip() {
        let lf = LockFile::parse(SAMPLE).unwrap();
        let serialized = lf.to_toml();
        let lf2 = LockFile::parse(&serialized).unwrap();
        assert_eq!(lf2.packages.len(), lf.packages.len());
        assert_eq!(lf2.packages[0].name, lf.packages[0].name);
        assert_eq!(lf2.packages[0].hash, lf.packages[0].hash);
    }

    #[test]
    fn upsert_updates_existing() {
        let mut lf = LockFile::parse(SAMPLE).unwrap();
        lf.upsert(LockedPackage {
            name: "tls".to_string(),
            version: "0.5.0".to_string(),
            hash: "sha256:newhash".to_string(),
            commit: None,
            git: None,
        });
        assert_eq!(lf.packages.len(), 2); // still 2
        assert_eq!(lf.get("tls").unwrap().version, "0.5.0");
    }

    #[test]
    fn upsert_adds_new() {
        let mut lf = LockFile::default();
        lf.upsert(LockedPackage {
            name: "foo".to_string(),
            version: "1.0.0".to_string(),
            hash: "sha256:aaa".to_string(),
            commit: None,
            git: None,
        });
        assert_eq!(lf.packages.len(), 1);
    }

    #[test]
    fn is_complete_check() {
        let lf = LockFile::parse(SAMPLE).unwrap();
        assert!(lf.is_complete(&["github.com/lab271/mvl-stdlib", "tls"]));
        assert!(!lf.is_complete(&["missing"]));
    }

    #[test]
    fn invalid_hash_prefix_rejected() {
        let bad = "[[package]]\nname = \"foo\"\nversion = \"1.0.0\"\nhash = \"md5:abc\"\n";
        let err = LockFile::parse(bad).unwrap_err();
        assert!(matches!(err, LockError::InvalidHash(_)));
    }

    #[test]
    fn missing_hash_returns_error() {
        let bad = "[[package]]\nname = \"foo\"\nversion = \"1.0.0\"\n";
        let err = LockFile::parse(bad).unwrap_err();
        assert!(matches!(err, LockError::MissingField(_)));
    }

    // ── New tests ─────────────────────────────────────────────────────────────

    // --- parse edge cases ---

    #[test]
    fn parse_empty_content_returns_empty_lockfile() {
        let lf = LockFile::parse("").unwrap();
        assert!(lf.packages.is_empty());
    }

    #[test]
    fn parse_only_comments_returns_empty() {
        let content = "# comment\n# another comment\n";
        let lf = LockFile::parse(content).unwrap();
        assert!(lf.packages.is_empty());
    }

    #[test]
    fn parse_crlf_line_endings() {
        // The parser uses .lines() which handles \r\n correctly on all platforms
        let content =
            "[[package]]\r\nname = \"foo\"\r\nversion = \"1.0.0\"\r\nhash = \"sha256:aaa\"\r\n";
        let lf = LockFile::parse(content).unwrap();
        assert_eq!(lf.packages.len(), 1);
        assert_eq!(lf.packages[0].name, "foo");
        assert_eq!(lf.packages[0].version, "1.0.0");
    }

    #[test]
    fn parse_unquoted_value_is_skipped() {
        // The parser only accepts quoted string values; bare values are silently skipped.
        // This means the field will be missing and produce a MissingField error for
        // required fields (name, version, hash).
        let content = "[[package]]\nname = unquoted\nversion = \"1.0.0\"\nhash = \"sha256:x\"\n";
        // 'name' has no quotes → not inserted → MissingField("name")
        let err = LockFile::parse(content).unwrap_err();
        assert!(matches!(err, LockError::MissingField(_)));
    }

    #[test]
    fn parse_hash_with_embedded_equals_sign() {
        // Values like "sha256:abc=def" must parse correctly; the parser splits on
        // the *first* `=` so the rest of the value is preserved.
        let content =
            "[[package]]\nname = \"foo\"\nversion = \"1.0.0\"\nhash = \"sha256:abc=def\"\n";
        let lf = LockFile::parse(content).unwrap();
        assert_eq!(lf.packages[0].hash, "sha256:abc=def");
    }

    #[test]
    fn parse_missing_name_returns_error() {
        let content = "[[package]]\nversion = \"1.0.0\"\nhash = \"sha256:abc\"\n";
        let err = LockFile::parse(content).unwrap_err();
        assert!(matches!(err, LockError::MissingField(ref f) if f == "name"));
    }

    #[test]
    fn parse_missing_version_returns_error() {
        let content = "[[package]]\nname = \"foo\"\nhash = \"sha256:abc\"\n";
        let err = LockFile::parse(content).unwrap_err();
        assert!(matches!(err, LockError::MissingField(ref f) if f == "version"));
    }

    // --- remove ---

    #[test]
    fn remove_package_by_name() {
        let mut lf = LockFile::parse(SAMPLE).unwrap();
        assert_eq!(lf.packages.len(), 2);
        lf.remove("tls");
        assert_eq!(lf.packages.len(), 1);
        assert!(lf.get("tls").is_none());
        assert!(lf.get("github.com/lab271/mvl-stdlib").is_some());
    }

    #[test]
    fn remove_nonexistent_is_noop() {
        let mut lf = LockFile::parse(SAMPLE).unwrap();
        let count_before = lf.packages.len();
        lf.remove("does-not-exist");
        assert_eq!(lf.packages.len(), count_before);
    }

    // --- get ---

    #[test]
    fn get_returns_none_for_missing_package() {
        let lf = LockFile::parse(SAMPLE).unwrap();
        assert!(lf.get("nonexistent").is_none());
    }

    // --- is_complete ---

    #[test]
    fn is_complete_empty_name_list_is_always_true() {
        let lf = LockFile::default();
        assert!(lf.is_complete(&[]));
    }

    #[test]
    fn is_complete_partial_match_returns_false() {
        let lf = LockFile::parse(SAMPLE).unwrap();
        assert!(!lf.is_complete(&["tls", "missing-pkg"]));
    }

    // --- to_toml omits optional fields ---

    #[test]
    fn to_toml_omits_commit_and_git_when_none() {
        let mut lf = LockFile::default();
        lf.upsert(LockedPackage {
            name: "bar".to_string(),
            version: "2.0.0".to_string(),
            hash: "sha256:xyz".to_string(),
            commit: None,
            git: None,
        });
        let toml = lf.to_toml();
        assert!(!toml.contains("commit ="), "commit should be absent");
        assert!(!toml.contains("git ="), "git should be absent");
    }

    #[test]
    fn to_toml_includes_commit_and_git_when_set() {
        let mut lf = LockFile::default();
        lf.upsert(LockedPackage {
            name: "baz".to_string(),
            version: "1.0.0".to_string(),
            hash: "sha256:abc".to_string(),
            commit: Some("cafebabe".to_string()),
            git: Some("https://example.com/pkg".to_string()),
        });
        let toml = lf.to_toml();
        assert!(toml.contains("commit = \"cafebabe\""));
        assert!(toml.contains("git = \"https://example.com/pkg\""));
    }

    // --- LockError Display ---

    #[test]
    fn lock_error_display_io() {
        let e = LockError::Io("/path".to_string(), "not found".to_string());
        assert!(e.to_string().contains("/path"));
        assert!(e.to_string().contains("not found"));
    }

    #[test]
    fn lock_error_display_missing_field() {
        let e = LockError::MissingField("hash".to_string());
        assert!(e.to_string().contains("hash"));
    }

    #[test]
    fn lock_error_display_invalid_hash() {
        let e = LockError::InvalidHash("md5:abc".to_string());
        assert!(e.to_string().contains("md5:abc"));
    }

    // --- load_or_empty on missing directory ---

    #[test]
    fn load_or_empty_returns_empty_when_file_absent() {
        let tmp = tempfile::tempdir().unwrap();
        // No mvl.lock file exists
        let lf = LockFile::load_or_empty(tmp.path());
        assert!(lf.packages.is_empty());
    }

    // --- write / load roundtrip ---

    #[test]
    fn write_then_load_roundtrip() {
        let tmp = tempfile::tempdir().unwrap();
        let mut lf = LockFile::default();
        lf.upsert(LockedPackage {
            name: "mypkg".to_string(),
            version: "3.0.0".to_string(),
            hash: "sha256:deadbeef".to_string(),
            commit: Some("abc123".to_string()),
            git: Some("https://example.com/mypkg".to_string()),
        });
        lf.write(tmp.path()).unwrap();

        let loaded = LockFile::load(tmp.path()).unwrap();
        assert_eq!(loaded.packages.len(), 1);
        let p = &loaded.packages[0];
        assert_eq!(p.name, "mypkg");
        assert_eq!(p.version, "3.0.0");
        assert_eq!(p.hash, "sha256:deadbeef");
        assert_eq!(p.commit.as_deref(), Some("abc123"));
        assert_eq!(p.git.as_deref(), Some("https://example.com/mypkg"));
    }
}
