// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Schuberg Philis

//! Generate Cargo project files for transpiled MVL programs.
//!
//! This module is part of the Phase 1 compilation pipeline described in ADR-0003
//! ("Compilation Strategy"): `mvl build` invokes `cargo build` on the generated
//! project, which requires a valid `Cargo.toml`.
//!
//! # Cargo.toml structure
//!
//! - Edition: 2021 (Rust stable baseline)
//! - Crate type: `[[bin]]` — MVL programs compile to native executables
//! - `mvl_runtime` dep: added when the program uses security labels or IFC types
//! - External crate deps: added for each `extern "rust"` block in the source
//!
//! Implements the Rust-target transpilation path described in ADR-0003.
//! Produces `Cargo.toml` and `src/main.rs` boilerplate for the generated crate.
//! Spec link: 000-parser Req 1 (compiler pipeline output).
//!
//! Satisfies ADR-0003 Phase 1 criterion 1: "`mvl build` produces a native binary".

/// Options for Cargo.toml generation.
pub struct CargoOptions<'a> {
    pub crate_name: &'a str,
    /// Whether the program uses `extern "rust"` blocks (adds mvl_runtime dep).
    pub use_mvl_runtime: bool,
    /// Extra crate names declared in `extern "rust"` blocks.
    pub extern_crates: Vec<String>,
}

impl<'a> CargoOptions<'a> {
    pub fn new(crate_name: &'a str) -> Self {
        Self {
            crate_name,
            use_mvl_runtime: false,
            extern_crates: Vec::new(),
        }
    }

    pub fn with_runtime(mut self) -> Self {
        self.use_mvl_runtime = true;
        self
    }
}

fn deps_section(opts: &CargoOptions<'_>) -> String {
    let mut lines = Vec::new();
    if opts.use_mvl_runtime {
        // Use path dep for local development; published crate once released.
        // Path is `./mvl_runtime` (inside the build dir) so each concurrent
        // build has its own copy — eliminates races on shared `/tmp/mvl_runtime`.
        lines.push(
            "mvl_runtime = { path = \"./mvl_runtime\" }  # MVL security labels and prelude"
                .to_string(),
        );
    }
    for krate in &opts.extern_crates {
        // TODO: pin to a specific version before publishing.
        lines.push(format!(
            "{krate} = \"0.1\"  # declared in extern \"rust\" block — pin version before publishing"
        ));
    }
    if lines.is_empty() {
        String::new()
    } else {
        format!("\n[dependencies]\n{}\n", lines.join("\n"))
    }
}

/// Emit `Cargo.toml` for a binary crate (program has `fn main`).
pub fn emit_cargo_toml_binary(crate_name: &str) -> String {
    emit_cargo_toml_binary_opts(&CargoOptions::new(crate_name))
}

pub fn emit_cargo_toml_binary_opts(opts: &CargoOptions<'_>) -> String {
    let deps = deps_section(opts);
    let crate_name = opts.crate_name;
    format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"

# Generated by MVL transpiler — do not edit manually (regenerate with `mvl build`)
{deps}"#
    )
}

/// Emit `Cargo.toml` for a library crate (no `fn main`).
pub fn emit_cargo_toml_library(crate_name: &str) -> String {
    emit_cargo_toml_library_opts(&CargoOptions::new(crate_name))
}

pub fn emit_cargo_toml_library_opts(opts: &CargoOptions<'_>) -> String {
    let deps = deps_section(opts);
    let crate_name = opts.crate_name;
    format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"

# Generated by MVL transpiler — do not edit manually (regenerate with `mvl build`)

[lib]
name = "{crate_name}"
path = "src/lib.rs"
{deps}"#
    )
}

/// Emit a stub `src/main.rs` for library crates that need a binary entry point.
pub fn emit_main_rs_stub(crate_name: &str) -> String {
    format!(
        r#"// Generated by MVL transpiler (Phase 1)
// No `fn main` in MVL source — library crate.
// Link against {crate_name} to use its functions.
fn main() {{
    println!("mvl library: {crate_name}");
}}
"#
    )
}

// Keep old name for callers that haven't migrated yet.
#[allow(dead_code)]
pub fn emit_cargo_toml(crate_name: &str) -> String {
    emit_cargo_toml_library(crate_name)
}

#[allow(dead_code)]
pub fn emit_main_rs(entry_fn: Option<&str>) -> String {
    match entry_fn {
        Some(name) => format!(
            r#"// Generated by MVL transpiler (Phase 1)
mod lib;
use lib::*;

fn main() {{
    {name}();
}}
"#
        ),
        None => emit_main_rs_stub("mvl_program"),
    }
}
