// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Schuberg Philis

//! Emit Rust function declarations from MVL [`FnDecl`] nodes.
//!
//! Phase 1 mappings:
//! - Effects (`! DB + Console`) → `/// # Effects: DB, Console` doc comment
//! - Totality (`total`) → `/// # Totality: total` doc comment
//! - Capabilities (`iso`, `val`, `ref`, `tag`) → `// capability: iso` comment on param
//! - Type params with constraints → Rust generic bounds
//! - Return refinement → `assert!` at end of body

use crate::mvl::backends::rust::emit_exprs::{emit_block_stmts, emit_expr};
use crate::mvl::backends::rust::emit_stmts::emit_mcdc_return_expr;
use crate::mvl::backends::rust::emit_types::{
    emit_label, emit_ref_expr_for_assert, emit_type_expr,
};
use crate::mvl::backends::rust::emitter::RustEmitter;
use crate::mvl::backends::rust::last_use::compute_last_uses;
use crate::mvl::parser::ast::{
    expr_to_ref_expr_ext, Block, Capability, Constraint, Expr, FnDecl, GenericParam, Param, Stmt,
    Totality, TypeExpr,
};
use crate::mvl::parser::lexer::Span;
use crate::mvl::passes::coverage::BranchKind;

/// Emit a function-parameter type.
///
/// MVL's `fn(T) -> U` is a bare Rust function pointer.  When used as a
/// function *parameter* the caller may pass a closure, which is not a bare
/// `fn` pointer.  Emitting `impl Fn(T) -> U` accepts both function pointers
/// and closures, matching MVL's intent.  The change is safe for all current
/// MVL constructs: `impl Fn` may not appear in struct fields or as a named
/// type-alias position, but those uses are not generated by the transpiler.
fn emit_fn_param_type(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Fn { params, ret, .. } => {
            let params_str: Vec<String> = params.iter().map(emit_type_expr).collect();
            format!("fn({}) -> {}", params_str.join(", "), emit_type_expr(ret))
        }
        _ => emit_type_expr(ty),
    }
}

pub fn emit_fn_decl(cg: &mut RustEmitter, fd: &FnDecl) {
    // Track current function name and test status for coverage metadata.
    cg.current_fn = fd.name.clone();
    cg.current_fn_is_test = fd.is_test;

    // Test functions are emitted inside a #[cfg(test)] mod tests block.
    // The caller (codegen) is responsible for grouping them; here we just
    // emit the #[test] attribute and a non-pub signature.
    // Retrieve borrow flags for this function (Phase B, Spec 009 Req 2).
    let borrows: Vec<Option<bool>> = cg
        .capability_params_map
        .get(&fd.name)
        .cloned()
        .unwrap_or_default();

    let mutated_params = collect_mutated_map_params(&fd.body);

    if fd.is_test {
        cg.line("#[test]");
        let generics = emit_generics_with_params(
            &fd.type_params,
            &fd.constraints,
            &fd.params,
            &fd.return_type,
        );
        let params_str = emit_params(&fd.params, &borrows, &mutated_params);
        let ret_str = emit_type_expr(&fd.return_type);
        cg.line(&format!(
            "fn {}{generics}({params_str}) -> {ret_str} {{",
            fd.name
        ));
        cg.push_indent();
        emit_fn_body(cg, fd);
        cg.pop_indent();
        cg.line("}");
        return;
    }

    // Doc comments for MVL-specific annotations that Rust cannot express directly
    if let Some(Totality::Total) = &fd.totality {
        cg.line("/// # Totality");
        cg.line("/// This function is declared `total` in MVL: it must terminate for all inputs.");
    }
    if !fd.effects.is_empty() {
        cg.line(&format!(
            "/// # Effects: {}",
            fd.effects
                .iter()
                .map(|e| e.to_string())
                .collect::<Vec<_>>()
                .join(", ")
        ));
        cg.line("/// MVL effect annotations — informational in Phase 1.");
    }

    // Function signature
    let generics = emit_generics_with_params(
        &fd.type_params,
        &fd.constraints,
        &fd.params,
        &fd.return_type,
    );
    let ret_str = emit_type_expr(&fd.return_type);

    if let Some(recv_ty) = &fd.receiver_type {
        // #928: Built-in types (String, List, Map, etc.) cannot have `impl` blocks
        // in Rust because they are defined outside the crate.  Emit their extension
        // methods as free functions so the UFCS dispatch table can call them.
        let is_builtin_type = matches!(
            recv_ty.as_str(),
            "String"
                | "Int"
                | "Float"
                | "Bool"
                | "Byte"
                | "UByte"
                | "UInt"
                | "List"
                | "Map"
                | "Set"
                | "Option"
                | "Result"
        );
        if !is_builtin_type {
            // Type-attached method (#868): emit inside `impl ReceiverType { … }`.
            // The `self` parameter (index 0) is replaced with `&self` in Rust.
            let rest_params = emit_params(
                fd.params.get(1..).unwrap_or(&[]),
                borrows.get(1..).unwrap_or(&[]),
                &mutated_params,
            );
            let params_str = if rest_params.is_empty() {
                "&self".to_string()
            } else {
                format!("&self, {rest_params}")
            };
            cg.line(&format!("impl {recv_ty} {{"));
            cg.push_indent();
            cg.line(&format!(
                "pub fn {}{generics}({params_str}) -> {ret_str} {{",
                fd.name
            ));
            cg.push_indent();
            // Fn-entry probe
            if let Some(id) = cg.alloc_branch(fd.span.line, BranchKind::FnEntry) {
                cg.emit_cov_hit(id);
            }
            for req_expr in &fd.requires {
                if let Some(req_pred) = expr_to_ref_expr_ext(req_expr, Span::default()) {
                    let pred_str = emit_ref_expr_for_assert(&req_pred, "self");
                    let msg = pred_str.replace('{', "{{").replace('}', "}}");
                    cg.line(&format!("assert!({pred_str}, \"requires: {msg}\");"));
                }
            }
            emit_fn_body(cg, fd);
            cg.pop_indent();
            cg.line("}");
            cg.pop_indent();
            cg.line("}");
            return;
        }
        // Fall through: emit as a free function with `self` as a regular parameter.
    }

    // #928: extension methods on built-in types are emitted as free functions
    // where `self` is renamed to `self_` (Rust keyword).
    let has_self_param = fd.receiver_type.is_some();
    if has_self_param {
        cg.self_as_free_param = true;
    }

    let params_str = emit_params(&fd.params, &borrows, &mutated_params);
    cg.line(&format!(
        "pub fn {}{generics}({params_str}) -> {ret_str} {{",
        fd.name
    ));
    cg.push_indent();
    // Fn-entry probe: records whether the function was ever called.
    if let Some(id) = cg.alloc_branch(fd.span.line, BranchKind::FnEntry) {
        cg.emit_cov_hit(id);
    }
    // Emit runtime precondition guards for `requires` clauses (Phase 4, #627).
    // These catch contract violations at runtime when the static checker deferred
    // to RuntimeCheck (e.g. when the predicate involves multiple parameters or
    // complex arithmetic that the solver could not prove).
    for req_expr in &fd.requires {
        if let Some(req_pred) = expr_to_ref_expr_ext(req_expr, Span::default()) {
            let pred_str = emit_ref_expr_for_assert(&req_pred, "self");
            let msg = pred_str.replace('{', "{{").replace('}', "}}");
            cg.line(&format!("assert!({pred_str}, \"requires: {msg}\");"));
        }
    }
    emit_fn_body(cg, fd);
    cg.pop_indent();
    cg.line("}");

    if has_self_param {
        cg.self_as_free_param = false;
    }
}

/// Emit the statements and return-refinement check for a function body.
fn emit_fn_body(cg: &mut RustEmitter, fd: &FnDecl) {
    // Phase A: compute last uses so emit_expr_as_arg can elide .clone() at move points.
    cg.last_uses = compute_last_uses(&fd.body);

    // Populate borrow_param_names so let-binding emission can add `.clone()`
    // when reading a field from a borrowed parameter (e.g. `acc.items`).
    cg.capability_param_names.clear();
    let borrows = cg
        .capability_params_map
        .get(&fd.name)
        .cloned()
        .unwrap_or_default();
    for (i, param) in fd.params.iter().enumerate() {
        if borrows.get(i).copied().flatten().is_some() {
            cg.capability_param_names.insert(param.name.clone());
        }
    }

    // #960: for HOF params (fn-typed parameters), temporarily insert their inner
    // parameter borrow flags into capability_params_map so that calls through
    // the fn pointer use `&x` instead of `x.clone().into()` for `val T` params.
    // Save the displaced entry (if any) so we can restore it on cleanup — a HOF
    // param name that collides with a top-level function name must not clobber it.
    let mut hof_param_entries: Vec<(String, Option<Vec<Option<bool>>>)> = Vec::new();
    for param in &fd.params {
        if let TypeExpr::Fn {
            params: fn_params, ..
        } = &param.ty
        {
            let flags: Vec<Option<bool>> = fn_params
                .iter()
                .map(|p| {
                    if let TypeExpr::Ref { mutable, .. } = p {
                        Some(*mutable)
                    } else {
                        None
                    }
                })
                .collect();
            if flags.iter().any(|b| b.is_some()) {
                let previous = cg.capability_params_map.insert(param.name.clone(), flags);
                hof_param_entries.push((param.name.clone(), previous));
            }
        }
    }

    let stmts = &fd.body.stmts;
    if stmts.is_empty() {
        // Unit-returning functions with an empty body are valid in Rust (implicit `()`).
        // Non-Unit empty bodies get a `todo!` placeholder so the generated code compiles.
        let is_unit =
            matches!(fd.return_type.as_ref(), TypeExpr::Base { name, .. } if name == "Unit");
        if !is_unit {
            cg.line("todo!(\"empty body\")");
        }
    } else {
        // Emit all but the last statement normally
        let (head, tail) = stmts.split_at(stmts.len() - 1);
        emit_block_stmts(cg, head);

        // Last statement: if it's a bare Expr statement, emit without semicolon
        // so it becomes the implicit return value.
        // Phase 4 (#627): when `ensures` clauses are present, wrap the tail value in a
        // `let _result = …` binding so we can assert postconditions before returning.
        let last = &tail[0];
        let is_unit =
            matches!(fd.return_type.as_ref(), TypeExpr::Base { name, .. } if name == "Unit");
        use crate::mvl::parser::ast::Stmt;
        let has_ensures = !fd.ensures.is_empty() && !is_unit;
        match last {
            Stmt::Expr { expr, .. } => {
                // Note: when emit_mcdc_return_expr returns true (Bool-returning functions),
                // `ensures` assertions are not emitted for that path. This is a known
                // limitation: Bool-return MC/DC coverage and ensures are not yet integrated.
                if !emit_mcdc_return_expr(cg, expr, &fd.return_type, expr.span().line) {
                    if has_ensures {
                        // Capture the return value so postcondition asserts can reference it.
                        // Use emit_expr_tail_with_return_type to preserve security-label
                        // wrapping (e.g. Secret<T> return types).
                        cg.indent();
                        cg.push("let _result = ");
                        emit_expr_tail_with_return_type(cg, expr, &fd.return_type, &fd.params);
                        cg.push(";");
                        cg.nl();
                        for ens_expr in &fd.ensures {
                            if let Some(ens_pred) = expr_to_ref_expr_ext(ens_expr, Span::default())
                            {
                                let pred_str = emit_ref_expr_for_assert(&ens_pred, "_result");
                                let msg = pred_str.replace('{', "{{").replace('}', "}}");
                                cg.line(&format!("assert!({pred_str}, \"ensures: {msg}\");"));
                            }
                        }
                        cg.line("_result");
                    } else {
                        cg.indent();
                        emit_expr_tail_with_return_type(cg, expr, &fd.return_type, &fd.params);
                        cg.nl();
                    }
                }
            }
            // Note: explicit `return` statements and other non-tail-expr last statements
            // are emitted as-is. `ensures` assertions are not injected for these paths;
            // the static checker handles postcondition verification for them at compile time.
            other => emit_block_stmts(cg, std::slice::from_ref(other)),
        }
    }

    // Return refinement: emit assert! before closing brace
    if let Some(pred) = &fd.return_refinement {
        let pred_str = emit_ref_expr_for_assert(pred, "_return_val");
        cg.line(&format!(
            "// return refinement: assert!({pred_str}) — checked by MVL type checker"
        ));
    }

    // #960: restore capability_params_map entries displaced above.
    for (name, previous) in hof_param_entries {
        match previous {
            Some(v) => {
                cg.capability_params_map.insert(name, v);
            }
            None => {
                cg.capability_params_map.remove(&name);
            }
        }
    }
}

// ── Generics ─────────────────────────────────────────────────────────────

/// Like `emit_generics` but also scans `params` to auto-add `Hash + Eq` for
/// type params used as Map/Set keys and `Clone` for Map value params.
///
/// This lets `std/collections.mvl` functions have real MVL bodies (using
/// method calls like `m.get(key)`) without requiring verbose where-clauses
/// that the MVL parser cannot fully express (e.g. `std::hash::Hash`).
fn emit_generics_with_params(
    type_params: &[GenericParam],
    constraints: &[Constraint],
    params: &[Param],
    return_ty: &TypeExpr,
) -> String {
    if type_params.is_empty() {
        return String::new();
    }
    // Build bounds map from explicit MVL where-clause constraints.
    let mut bounds: std::collections::HashMap<String, Vec<String>> =
        std::collections::HashMap::new();
    for c in constraints {
        bounds
            .entry(c.name.clone())
            .or_default()
            .push(c.bound.clone());
    }

    // Auto-add Hash+Eq for Map/Set key type params and Clone for Map value params.
    // Scan both parameters and return type so that functions whose Map appears
    // only in the return position (e.g. group_by) also get the correct bounds.
    collect_map_set_bounds(params, &mut bounds);
    collect_type_bounds(return_ty, &mut bounds);

    let params_out: Vec<String> = type_params
        .iter()
        .map(|p| match p {
            GenericParam::Const(name, _ty) => format!("const {name}: usize"),
            GenericParam::Type(name) => {
                let bs = bounds.get(name.as_str()).cloned().unwrap_or_default();
                if bs.is_empty() {
                    name.clone()
                } else {
                    format!("{name}: {}", bs.join(" + "))
                }
            }
        })
        .collect();
    format!("<{}>", params_out.join(", "))
}

/// Scan function parameters for `Map[K, V]` and `Set[T]` types and add the
/// Rust trait bounds needed for HashMap/HashSet to function correctly.
fn collect_map_set_bounds(
    params: &[Param],
    bounds: &mut std::collections::HashMap<String, Vec<String>>,
) {
    for p in params {
        collect_type_bounds(&p.ty, bounds);
    }
}

fn collect_type_bounds(ty: &TypeExpr, bounds: &mut std::collections::HashMap<String, Vec<String>>) {
    match ty {
        TypeExpr::Base { name, args, .. } => {
            match name.as_str() {
                "Map" if args.len() == 2 => {
                    // Map[K, V]: K must be Hash+Eq+Clone (Clone required because
                    // the transpiler emits `.mvl_get(key.clone())` at call sites),
                    // V must be Clone.
                    add_bound_if_type_param(&args[0], "std::hash::Hash", bounds);
                    add_bound_if_type_param(&args[0], "std::cmp::Eq", bounds);
                    add_bound_if_type_param(&args[0], "Clone", bounds);
                    add_bound_if_type_param(&args[1], "Clone", bounds);
                    // Recurse in case args are themselves generic types.
                    for a in args {
                        collect_type_bounds(a, bounds);
                    }
                }
                "Set" if args.len() == 1 => {
                    // Set[T]: T must be Hash+Eq+Clone.
                    add_bound_if_type_param(&args[0], "std::hash::Hash", bounds);
                    add_bound_if_type_param(&args[0], "std::cmp::Eq", bounds);
                    add_bound_if_type_param(&args[0], "Clone", bounds);
                }
                _ => {
                    for a in args {
                        collect_type_bounds(a, bounds);
                    }
                }
            }
        }
        TypeExpr::Ref { inner, .. } => collect_type_bounds(inner, bounds),
        _ => {}
    }
}

/// If `ty` is a bare type-parameter name (single uppercase letter or camel-case
/// ident with no args), add the given bound for that name.
fn add_bound_if_type_param(
    ty: &TypeExpr,
    bound: &str,
    bounds: &mut std::collections::HashMap<String, Vec<String>>,
) {
    if let TypeExpr::Base { name, args, .. } = ty {
        if args.is_empty() && !is_concrete_type(name) {
            let entry = bounds.entry(name.clone()).or_default();
            if !entry.iter().any(|b| b == bound) {
                entry.push(bound.to_string());
            }
        }
    }
}

/// Concrete MVL built-in types that are never generic type parameters.
fn is_concrete_type(name: &str) -> bool {
    matches!(
        name,
        "Int"
            | "Float"
            | "Bool"
            | "String"
            | "Char"
            | "Byte"
            | "Unit"
            | "Never"
            | "List"
            | "Map"
            | "Set"
            | "Option"
            | "Result"
    )
}

// ── Parameters ───────────────────────────────────────────────────────────

/// Collect names of Map/Set parameters that are mutated in the body (i.e. have
/// `.insert(…)` or `.remove(…)` called on them).  Only these need `mut` in the
/// Rust signature; read-only Map/Set params must not get `mut` to avoid Rust's
/// "variable does not need to be mutable" warning.
fn collect_mutated_map_params(body: &Block) -> std::collections::HashSet<String> {
    let mut out = std::collections::HashSet::new();
    scan_stmts_for_mut_calls(&body.stmts, &mut out);
    out
}

fn scan_stmts_for_mut_calls(stmts: &[Stmt], out: &mut std::collections::HashSet<String>) {
    for stmt in stmts {
        match stmt {
            Stmt::Expr { expr, .. }
            | Stmt::Return {
                value: Some(expr), ..
            } => {
                scan_expr_for_mut_calls(expr, out);
            }
            Stmt::Let { init, .. } => scan_expr_for_mut_calls(init, out),
            Stmt::Assign { value, .. } => scan_expr_for_mut_calls(value, out),
            Stmt::If {
                cond, then, else_, ..
            } => {
                scan_expr_for_mut_calls(cond, out);
                scan_stmts_for_mut_calls(&then.stmts, out);
                if let Some(crate::mvl::parser::ast::ElseBranch::Block(b)) = else_ {
                    scan_stmts_for_mut_calls(&b.stmts, out);
                }
            }
            Stmt::For { body, iter, .. } => {
                scan_expr_for_mut_calls(iter, out);
                scan_stmts_for_mut_calls(&body.stmts, out);
            }
            Stmt::While { cond, body, .. } => {
                scan_expr_for_mut_calls(cond, out);
                scan_stmts_for_mut_calls(&body.stmts, out);
            }
            _ => {}
        }
    }
}

fn scan_expr_for_mut_calls(expr: &Expr, out: &mut std::collections::HashSet<String>) {
    match expr {
        Expr::MethodCall {
            receiver,
            method,
            args,
            ..
        } => {
            // insert/remove/retain are mutating Map/Set methods
            if matches!(method.as_str(), "insert" | "remove" | "retain") {
                if let Expr::Ident(name, _) = receiver.as_ref() {
                    out.insert(name.clone());
                }
            }
            scan_expr_for_mut_calls(receiver, out);
            for a in args {
                scan_expr_for_mut_calls(a, out);
            }
        }
        Expr::FnCall { args, .. } => {
            for a in args {
                scan_expr_for_mut_calls(a, out);
            }
        }
        _ => {}
    }
}

fn emit_params(
    params: &[Param],
    borrows: &[Option<bool>],
    mutated_params: &std::collections::HashSet<String>,
) -> String {
    params
        .iter()
        .enumerate()
        .map(|(i, p)| {
            // Phase B: if this param is an inferred borrow (not already TypeExpr::Ref),
            // wrap the emitted type in `&` or `&mut `.
            let ty_str = match borrows.get(i).copied().flatten() {
                Some(mutable) if !matches!(p.ty, TypeExpr::Ref { .. }) => {
                    if mutable {
                        format!("&mut {}", emit_fn_param_type(&p.ty))
                    } else {
                        format!("&{}", emit_fn_param_type(&p.ty))
                    }
                }
                _ => emit_fn_param_type(&p.ty),
            };
            // Capability annotation as a comment prefix: kept in name for now
            let cap_comment = match &p.capability {
                Some(Capability::Iso) => "/* iso */ ",
                Some(Capability::Val) => "/* val */ ",
                Some(Capability::Ref) => "/* ref */ ",
                Some(Capability::Tag) => "/* tag */ ",
                None => "",
            };
            // Map/Set value parameters need `mut` in Rust only when the body
            // actually calls mutating methods (insert/remove) on them.
            let is_mutated_map_or_set = borrows.get(i).copied().flatten().is_none()
                && matches!(
                    &p.ty,
                    TypeExpr::Base { name, .. } if name == "Map" || name == "Set"
                )
                && mutated_params.contains(&p.name);
            // A param is mutable in Rust when it has a `ref` or `iso` capability,
            // or when it is a Map/Set whose contents are mutated.
            let has_ref_cap = matches!(
                p.capability,
                Some(crate::mvl::parser::ast::Capability::Ref)
                    | Some(crate::mvl::parser::ast::Capability::Iso)
            );
            let mut_prefix = if has_ref_cap || is_mutated_map_or_set {
                "mut "
            } else {
                ""
            };
            // #928: `self` is a keyword in Rust — rename to `self_` in free functions.
            let param_name = if p.name == "self" {
                "self_"
            } else {
                p.name.as_str()
            };
            format!("{cap_comment}{mut_prefix}{param_name}: {ty_str}")
        })
        .collect::<Vec<_>>()
        .join(", ")
}

// ── Tail expression emitter ───────────────────────────────────────────────

/// Emit an expression as the tail (implicit return) of a function body.
/// When the declared return type is a security label wrapper (e.g. `Secret<String>`),
/// literal expressions are wrapped with the appropriate constructor so that the
/// generated Rust code type-checks without manual coercions.
///
/// This handles common stub patterns like:
/// ```mvl
/// fn generate_token(id: UserId) -> Secret<String> { "token" }
/// ```
/// → `Secret("token".to_string())`
fn emit_expr_tail_with_return_type(
    cg: &mut RustEmitter,
    expr: &Expr,
    return_type: &TypeExpr,
    params: &[Param],
) {
    // Unit-returning functions: tail expression must be discarded (semicolon) so
    // that collection mutators like `m.insert()` or `s.remove()` — which return
    // non-unit values in Rust — don't cause type mismatches.
    if matches!(return_type, TypeExpr::Base { name, .. } if name == "Unit") {
        emit_expr(cg, expr);
        cg.push(";");
        return;
    }
    match return_type {
        TypeExpr::Labeled { label, .. } if is_raw_value(expr, params) => {
            // Wrap only when the expression is a raw (unlabeled) value:
            // - literal → always raw
            // - ident that is a non-labeled parameter → raw
            let label_name = emit_label(label.as_str());
            cg.push(&format!("{label_name}("));
            emit_expr(cg, expr);
            cg.push(")");
            return;
        }
        TypeExpr::Labeled { .. }
            if matches!(expr, Expr::FnCall { .. } | Expr::MethodCall { .. }) =>
        {
            // Function call returning a plain value inside a labeled-return function
            // (e.g. `call_lex_counts(src.into())` in a `-> Clean<Counts>` fn).
            // `.into()` lifts the result via From<T> for Label<T>; also a no-op if
            // the call already returns the labeled type (From<T> for T blanket impl).
            emit_expr(cg, expr);
            cg.push(".into()");
            return;
        }
        TypeExpr::Result { ok, .. } => {
            // Ok(x) where x should be Labeled and x is a raw value: emit Ok(Label(x))
            if let TypeExpr::Labeled { label, .. } = ok.as_ref() {
                if let Expr::FnCall { name, args, .. } = expr {
                    if name == "Ok" && args.len() == 1 && is_raw_value(&args[0], params) {
                        let label_name = emit_label(label.as_str());
                        cg.push("Ok(");
                        cg.push(&format!("{label_name}("));
                        emit_expr(cg, &args[0]);
                        cg.push("))");
                        return;
                    }
                }
            }
        }
        _ => {}
    }
    emit_expr(cg, expr);
}

/// Returns true when an expression produces a raw (non-labeled) value that needs
/// to be wrapped in a security label constructor.
///
/// - Literals are always raw.
/// - An identifier is raw when it refers to a function parameter whose declared
///   type has no security label (e.g. `f: Float` is raw; `v: Public<Float>` is not).
fn is_raw_value(expr: &Expr, params: &[Param]) -> bool {
    match expr {
        Expr::Literal(_, _) => true,
        Expr::Ident(name, _) => {
            // Check if this name is a function parameter with a non-labeled type
            params
                .iter()
                .any(|p| &p.name == name && !is_labeled_type(&p.ty))
        }
        _ => false,
    }
}

/// Returns true when the type is a direct security label wrapper (no wrapping needed).
fn is_labeled_type(ty: &TypeExpr) -> bool {
    matches!(ty, TypeExpr::Labeled { .. })
}
