//! bridge.rs — pkg.tui raw-terminal implementation
//!
//! Implements the `extern "rust"` functions declared in src/internal/ffi.mvl.
//!
//! Design: std-only, no external crate dependencies.
//! - Raw mode: `stty -echo -icanon min 1 time 0` (POSIX, always available)
//! - Output:   ANSI/VT100 escape sequences via stdout
//! - Input:    blocking byte-read from stdin; timeout via a background thread
//!
//! Phase 4: replace stty + ANSI with crossterm for Windows support and
//! richer widgets (ratatui). Add `crossterm = "0.28"` to mvl.toml [native].

use std::io::{Read, Write, stdin, stdout};
use std::process::Command;
use std::sync::atomic::{AtomicBool, Ordering};

// ── Global raw-mode flag ───────────────────────────────────────────────────────

static RAW_MODE: AtomicBool = AtomicBool::new(false);

// ── Terminal lifecycle ────────────────────────────────────────────────────────

// `Terminal` is generated by the MVL transpiler from pkg.tui/src/core.mvl:
//   pub type Terminal = struct { _handle: Int }
// We reference it as `crate::Terminal` — do NOT redefine it here.
use crate::Terminal;

#[no_mangle]
pub extern "Rust" fn tui_init() -> i64 {
    let ok = Command::new("stty")
        .args(["-echo", "-icanon", "min", "1", "time", "0"])
        .stdin(std::process::Stdio::inherit())
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    if !ok {
        return 0;
    }
    RAW_MODE.store(true, Ordering::SeqCst);
    // Hide cursor; switch to alternate screen
    print!("\x1b[?25l\x1b[?1049h");
    stdout().flush().ok();
    1
}

#[no_mangle]
pub extern "Rust" fn tui_drop() {
    if RAW_MODE.swap(false, Ordering::SeqCst) {
        // Leave alternate screen; show cursor; restore cooked mode
        print!("\x1b[?1049l\x1b[?25h");
        stdout().flush().ok();
        Command::new("stty")
            .arg("sane")
            .stdin(std::process::Stdio::inherit())
            .status()
            .ok();
    }
}

// ── Output ────────────────────────────────────────────────────────────────────

#[no_mangle]
pub extern "Rust" fn tui_clear() {
    // ED2 (erase entire display) + move to (1,1)
    print!("\x1b[2J\x1b[H");
    stdout().flush().ok();
}

#[no_mangle]
pub extern "Rust" fn tui_set_cursor(row: i64, col: i64) {
    print!("\x1b[{};{}H", row, col);
    stdout().flush().ok();
}

#[no_mangle]
pub extern "Rust" fn tui_print(text: String, bold: bool, underline: bool, fg_color: i64) {
    let bold_on      = if bold      { "\x1b[1m" } else { "" };
    let underline_on = if underline { "\x1b[4m" } else { "" };
    let color_on     = ansi_fg(fg_color);
    print!("{}{}{}{}\x1b[0m", bold_on, underline_on, color_on, text);
    stdout().flush().ok();
}

fn ansi_fg(n: i64) -> &'static str {
    match n {
        1 => "\x1b[30m", // Black
        2 => "\x1b[31m", // Red
        3 => "\x1b[32m", // Green
        4 => "\x1b[33m", // Yellow
        5 => "\x1b[34m", // Blue
        6 => "\x1b[35m", // Magenta
        7 => "\x1b[36m", // Cyan
        8 => "\x1b[37m", // White
        _ => "",          // Default
    }
}

#[no_mangle]
pub extern "Rust" fn tui_size() -> i64 {
    // `stty size` prints "rows cols\n"
    let out = Command::new("stty")
        .arg("size")
        .stdin(std::process::Stdio::inherit())
        .output();
    if let Ok(out) = out {
        let s = String::from_utf8_lossy(&out.stdout);
        let parts: Vec<&str> = s.trim().split_whitespace().collect();
        if parts.len() == 2 {
            if let (Ok(rows), Ok(cols)) =
                (parts[0].parse::<i64>(), parts[1].parse::<i64>())
            {
                return rows * 1000 + cols;
            }
        }
    }
    24 * 1000 + 80 // safe fallback: 24×80
}

// ── Input ─────────────────────────────────────────────────────────────────────

#[no_mangle]
pub extern "Rust" fn tui_read_key() -> String {
    read_one_key()
}

#[no_mangle]
pub extern "Rust" fn tui_read_key_timeout(millis: i64) -> String {
    use std::sync::mpsc;
    use std::thread;
    use std::time::Duration;

    let (tx, rx) = mpsc::channel::<String>();
    thread::spawn(move || {
        tx.send(read_one_key()).ok();
    });
    rx.recv_timeout(Duration::from_millis(millis.max(0) as u64))
        .unwrap_or_default()
}

// ── Key reading ───────────────────────────────────────────────────────────────

fn read_one_key() -> String {
    let mut b = [0u8; 1];
    if stdin().read(&mut b).unwrap_or(0) == 0 {
        return "Unknown".to_string();
    }
    match b[0] {
        b'\r' | b'\n' => "Enter".to_string(),
        127 => "Backspace".to_string(),
        27 => read_escape_sequence(),
        c if c >= 0x20 => {
            // Printable ASCII
            String::from_utf8(vec![c]).unwrap_or_else(|_| "Unknown".to_string())
        }
        _ => "Unknown".to_string(),
    }
}

fn read_escape_sequence() -> String {
    // Try to read up to 2 more bytes (CSI sequences: ESC [ X)
    // Use a brief non-blocking read: set stdin to non-blocking, try, restore.
    // Simpler: read with timeout via a short stty min 0 time 1 (1/10 sec).
    // Even simpler for Phase 7: just do a blocking read of 2 bytes and
    // accept that lone ESC keys are indistinguishable from arrow prefixes.
    let mut seq = [0u8; 2];
    // Temporarily allow zero-wait reads
    Command::new("stty")
        .args(["min", "0", "time", "1"])
        .stdin(std::process::Stdio::inherit())
        .status()
        .ok();
    let n = stdin().read(&mut seq).unwrap_or(0);
    // Restore raw settings
    Command::new("stty")
        .args(["-echo", "-icanon", "min", "1", "time", "0"])
        .stdin(std::process::Stdio::inherit())
        .status()
        .ok();

    if n >= 2 && seq[0] == b'[' {
        return match seq[1] {
            b'A' => "Up".to_string(),
            b'B' => "Down".to_string(),
            b'C' => "Right".to_string(),
            b'D' => "Left".to_string(),
            b'3' => "Delete".to_string(), // ESC[3~ — need one more byte, skip
            _    => "Escape".to_string(),
        };
    }
    "Escape".to_string()
}
