//! Rust implementations of `std.args` stdlib functions.
//!
//! Provides real CLI argument and environment access for the stubs declared
//! in `std/args.mvl`. Re-exported via `mvl_runtime::prelude::*`.
//!
//! ## Struct-derived parsing
//!
//! `args.parse<T>()` derives a CLI parser from the struct shape at compile time.
//! The MVL transpiler generates `impl ParseFromArgs for T` for each concrete
//! struct with parseable fields. This backing function calls into that impl:
//!
//! ```ignore
//! pub fn parse<T: ParseFromArgs>() -> Result<T, String> {
//!     T::parse_from_args()
//! }
//! ```

use crate::ifc::{Clean, Tainted};

/// Marker trait for structs that can be parsed from command-line arguments.
///
/// Implemented automatically by the MVL transpiler for every concrete struct
/// whose fields all have parseable types (`Int`, `Float`, `String`, `Bool`,
/// `Option<T>`, and refined variants of the above).
///
/// Field names map directly to flag names: `port` → `--port`.
/// `Bool` fields become presence flags; `Option<T>` fields are optional.
pub trait ParseFromArgs: Sized {
    /// Parse `Self` from the process's command-line arguments.
    ///
    /// Returns `Ok(value)` when all required flags are present and all
    /// refinement predicates are satisfied; `Err(message)` otherwise.
    fn parse_from_args() -> Result<Self, String>;
}

/// Parse command-line arguments into struct `T`.
///
/// Delegates to `T::parse_from_args()`, which is generated by the MVL
/// transpiler from the struct's field declarations.
///
/// Implements the Rust backing for `std/args.mvl::parse`.
pub fn parse<T: ParseFromArgs>() -> Result<T, String> {
    T::parse_from_args()
}

/// Scan command-line arguments for `--<name> <value>` and return the value.
///
/// Searches `std::env::args()` for the flag `--<name>` and returns the
/// following argument as `Tainted<String>` (untrusted external input).
/// Returns `None` if the flag is absent or has no following argument.
///
/// Implements the Rust backing for `std/args.mvl::get_arg`.
pub fn get_arg(name: Clean<String>) -> Option<Tainted<String>> {
    let flag = format!("--{}", *name);
    let args: Vec<String> = std::env::args().collect();
    for i in 0..args.len().saturating_sub(1) {
        if args[i] == flag {
            return Some(Tainted(args[i + 1].clone()));
        }
    }
    None
}

/// Return all command-line arguments (excluding the program name) as Tainted values.
///
/// Implements the Rust backing for `std/args.mvl::get_args`.
pub fn get_args() -> Vec<Tainted<String>> {
    std::env::args().skip(1).map(Tainted).collect()
}

/// Read an environment variable by name.
///
/// Returns `None` if the variable is not set.
/// Returns `Tainted<String>` because environment variables are externally controlled.
///
/// Implements the Rust backing for `std/args.mvl::get_env`.
pub fn get_env(name: Clean<String>) -> Option<Tainted<String>> {
    std::env::var(&*name).ok().map(Tainted)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{LazyLock, Mutex};

    // Serialise tests that mutate the process environment.
    // std::env::set_var / remove_var are not thread-safe; cargo runs unit tests
    // in parallel by default, so all env-mutating tests must hold this lock.
    static ENV_LOCK: LazyLock<Mutex<()>> = LazyLock::new(|| Mutex::new(()));

    #[test]
    fn get_arg_returns_none_for_unknown_flag() {
        // In unit tests the binary name is the test runner — no --mvl-unknown flag.
        let name = Clean("mvl-unknown-flag-xyz".to_string());
        assert!(get_arg(name).is_none());
    }

    #[test]
    fn get_args_returns_vec() {
        // Verify it doesn't panic and that each element is Tainted.
        let args = get_args();
        // All elements must be Tainted<String> (the collect() type guarantees this,
        // but we also verify the returned value is usable).
        assert!(args.iter().all(|a| !a.0.is_empty() || a.0.is_empty())); // type check
    }

    #[test]
    fn get_env_returns_none_for_unknown_var() {
        let name = Clean("MVL_NONEXISTENT_VAR_XYZ_12345".to_string());
        assert!(get_env(name).is_none());
    }

    #[test]
    #[allow(deprecated)]
    fn get_env_returns_value_when_set() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        // Held under ENV_LOCK — serialised against all other env-mutating tests.
        std::env::set_var("MVL_TEST_GET_ENV", "hello");
        let name = Clean("MVL_TEST_GET_ENV".to_string());
        let val = get_env(name);
        assert!(val.is_some());
        assert_eq!(val.unwrap().0, "hello");
        std::env::remove_var("MVL_TEST_GET_ENV");
    }
}
